//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Super Jukebox.rc
//
#define IDS_APP_NAME                    1
#define IDC_STATUS_BAR                  2
#define IDC_BUTTON_ADD                  3
#define IDC_BUTTON_REMOVE               4
#define IDC_BUTTON_ADDALL               5
#define IDC_BUTTON_REMOVEALL            6
#define IDC_BUTTON_PLAY                 7
#define IDC_BUTTON_PAUSE                8
#define IDC_BUTTON_STOP                 9
#define IDC_BUTTON_PREVIOUS             10
#define IDC_BUTTON_NEXT                 11
#define IDR_MENU_SUPER_JUKEBOX          12
#define IDR_ACCELERATOR_SUPER_JUKEBOX   13
#define IDC_LIST_FILELIST               15
#define IDC_LIST_PLAYLIST               16
#define IDC_EDIT_FIND_WHAT              18
#define IDC_COMBO_SEARCH_COLUMN         19
#define IDC_CHECK_MATCH_WHOLE_WORD_ONLY 20
#define IDC_CHECK_MATCH_CASE            21
#define IDC_RADIO_FIND_UP               22
#define IDC_RADIO_FIND_DOWN             23
#define IDC_EDIT_GOTO_SONG_NUMBER       24
#define IDC_SPIN_GOTO_SONG_NUMBER       25
#define IDC_TOOL_BAR                    26
#define IDC_STATIC_ADDFILES             27
#define IDC_PROGRESS_ADDFILES           28
#define IDC_RADIO_INDEFINITE            30
#define IDC_RADIO_UNIVERSAL             31
#define IDC_RADIO_INDIVIDUAL            32
#define IDC_EDIT_UNI_LENGTH             33
#define IDC_SPIN_UNI_LENGTH             34
#define IDC_EDIT_UNI_FADE               35
#define IDC_SPIN_UNI_FADE               36
#define IDC_CHECK_AUTO_REWIND           39
#define IDC_CHECK_RANDOMIZE             41
#define IDC_CHECK_DETECT_INACTIVITY     42
#define IDC_CHECK_USE_SKIN              43
#define IDC_COMBO_SKIN_LAYOUT           44
#define IDC_EDIT_SKIN_FILE              45
#define IDC_BUTTON_BROWSE_SKIN          46
#define IDC_COMBO_SAMPLE_RATE           60
#define IDC_COMBO_INTERPOLATION         61
#define IDC_EDIT_PREAMP                 62
#define IDC_SPIN_PREAMP                 63
#define IDC_EDIT_BUFFER_LENGTH          64
#define IDC_SPIN_BUFFER_LENGTH          65
#define IDC_COMBO_PRIORITY_LEVEL        66
#define IDC_RADIO_8BIT                  67
#define IDC_RADIO_16BIT                 68
#define IDC_RADIO_MONO                  69
#define IDC_RADIO_STEREO                70
#define IDC_RADIO_APR_OFF               71
#define IDC_RADIO_APR_ON                72
#define IDC_CHECK_USE_LOW_PASS_FILTER   73
#define IDC_CHECK_USE_OLD_SCHOOL_BRE    74
#define IDC_EDIT_PLAYLIST_LABEL         75
#define IDC_TOOLBAR_PAGER               76
#define IDC_VIS_WINDOW                  77
#define IDC_SOURCE_BAR                  78
#define IDC_REBAR                       79
#define IDC_BUTTON_WAVDUMP              80
#define IDC_BUTTON_AW                   81
#define IDC_BUTTON_FILTERVIEW           82
#define IDC_BUTTON_LAYOUT               83
#define IDC_BUTTON_VISMODE              84
#define IDI_SUPER_JUKEBOX               100
#define IDD_ABOUTBOX                    101
#define IDM_ALWAYSONTOP                 101
#define IDD_FIND                        102
#define IDD_GOTO                        103
#define IDB_COLOR_ICONS                 104
#define IDB_GRAY_ICONS                  105
#define IDD_ADDFILES                    106
#define IDD_PLAYLIST                    107
#define IDD_CONFIGURATION               109
#define IDD_PLAYER                      111
#define IDD_SKIN                        112
#define IDD_VISUALIZATION               116
#define IDB_DOWNUPARROWS                122
#define IDD_FILTER                      123
#define IDD_TOOLBAR_CUSTOMIZE           124
#define IDD_WARNING                     125
#define IDD_VIEW                        126
#define IDD_MISC                        127
#define IDD_PROGRAM                     128
#define IDD_CPL                         129
#define IDD_ACTIVEWALLPAPER             131
#define IDI_ICON1                       132
#define IDB_ONEUPCOLOR                  134
#define IDB_ONEUPGRAY                   135
#define IDD_BETABOX                     136
#define IDC_TREE_CONFIGURATION          1000
#define IDC_CHECK_NOMORE                1001
#define IDC_CHECK_PC_FILE               1001
#define IDC_CHECK_AUTOLOAD_PLAYLIST     1001
#define IDC_RADIO_32BIT                 1002
#define IDC_BUTTON_FILTER_REMOVE        1003
#define IDC_BUTTON_TC_ADD               1003
#define IDC_BUTTON_ADD_SMG              1003
#define IDC_CHECK_BLEND_SKIN            1004
#define IDC_BUTTON_BLENDING_COLOR       1005
#define IDC_SLIDER_BLENDING_LEVEL       1006
#define IDC_STATIC_BLENDING_LEVEL       1007
#define IDC_BUTTON_TEXT_COLOR           1008
#define IDC_CHECK_ALWAYS_USE_PROGRAM_SKIN 1009
#define IDC_STATIC_ADDFILES_TITLE       1010
#define IDC_RADIO_FILTER_AND            1022
#define IDC_RADIO_FILTER_OR             1023
#define IDC_LIST_TC_LEFT                1024
#define IDC_LIST_TC_RIGHT               1025
#define IDC_BUTTON_TC_REMOVE            1026
#define IDC_BUTTON_TC_MOVEUP            1027
#define IDC_BUTTON_TC_MOVEDOWN          1028
#define IDC_STATIC_ICON                 1029
#define IDC_CHECK_PC_TITLE              1033
#define IDC_CHECK_PC_GAME               1034
#define IDC_CHECK_PC_ARTIST             1035
#define IDC_CHECK_PC_DUMPER             1036
#define IDC_CHECK_PC_DATE               1037
#define IDC_CHECK_PC_COMMENT            1038
#define IDC_CHECK_PC_LENGTH             1039
#define IDC_CHECK_PC_FADE               1040
#define IDC_CHECK_FULLROWSELECT         1042
#define IDC_CHECK_SHOWGRIDLINES         1043
#define IDC_CHECK_TITLEBAR              1044
#define IDC_CHECK_MENU                  1045
#define IDC_CHECK_TOOLBAR               1046
#define IDC_CHECK_FILELIST              1047
#define IDC_CHECK_PLAYLIST              1048
#define IDC_CHECK_VISUALIZATION         1049
#define IDC_CHECK_STATUSBAR             1050
#define IDC_CHECK_TASKBAR               1051
#define IDC_CHECK_SYSTRAY               1052
#define IDC_CHECK_AUTOPLAY_SONG         1053
#define IDC_CHECK_AUTOSIZE_COLUMNS      1054
#define IDC_CHECK_MINIMIZETOSYSTRAY     1055
#define IDC_SLIDER_SPECTRUM_SIZE        1056
#define IDC_SLIDER_VIS_RATE             1057
#define IDC_STATIC_SPECTRUM_SIZE        1058
#define IDC_STATIC_VIS_RATE             1059
#define IDC_CHECK_READ_ID666_TAGS       1060
#define IDC_CHECK_SAVE_ID666_TAGS       1061
#define IDC_BUTTON_ADD_DI               1062
#define IDC_BUTTON_ADD_QLI              1063
#define IDC_COMBO_MAIN_THREAD_PRIORITY  1064
#define IDC_COMBO_PROCESS_PRIORITY      1065
#define IDC_SLIDER_CPL_SPEED            1066
#define IDC_SLIDER_CPL_PITCH            1067
#define IDC_SLIDER_CPL_MAINSS           1068
#define IDC_SLIDER_CPL_ECHOSS           1069
#define IDC_STATIC_CPL_SPEED            1070
#define IDC_STATIC_CPL_PITCH            1071
#define IDC_STATIC_CPL_MAINSS           1072
#define IDC_STATIC_CPL_ECHOSS           1073
#define IDC_COMBO_MIXING_MODE           1074
#define IDC_LIST_AW                     1075
#define IDC_BUTTON_AW_CONFIGURE         1076
#define IDC_BUTTON_AW_ABOUT             1077
#define IDC_CHECK_OUTPUTTOWAV           1078
#define IDC_EDIT_WAVDIR                 1080
#define IDC_BUTTON_BROWSEFORWAVDIR      1081
#define IDC_CHECK_OUTPUTWITHSOUND       1082
#define IDC_COMBO_AW_PRIORITY           1083
#define IDC_CHECK_AW_DBLBUF             1084
#define IDC_CHECK_SURROUNDSOUND         1085
#define IDC_CHECK_CPL                   1086
#define IDC_EDIT_STATISTICS             1087
#define IDC_CHECK_DISPLAYTOOLTIPS       1088
#define IDC_EDIT_WARNING                1089
#define IDC_CHECK_USEFASTSEEK           1090
#define IDC_CHECK_LOCATIONBAR           1091
#define IDC_STATIC_COREINFO             1092
#define IDC_BUTTON_HOMEPAGE             1094
#define IDC_BUTTON_MAILTO               1095
#define IDC_BUTTON_ZDSPCARCHIVE         1096
#define IDC_BUTTON_SNESAMPSPCARCHIVE    1097
#define IDC_BUTTON_SETDEFAULT           1098
#define IDC_BUTTON_RESET                1099
#define IDC_LIST_ASSOCEXT               1100
#define IDC_BUTTON_SELALL               1101
#define IDC_BUTTON_SELNONE              1102
#define IDC_CHECK_REGTYPES              1103
#define IDC_RADIO_APR_INC               1104
#define IDC_CHECK_REVERSE_STEREO        1105
#define IDC_CHECK_SHOWVISLABELS         1106
#define IDC_COMBO_VISCOLSCHEME          1107
#define IDC_COMBO_VISCOLITEM            1108
#define IDC_BUTTON_VISCOL1              1109
#define IDC_BUTTON_VISCOL2              1110
#define IDC_COMBO_SYSTRAYCMD            1111
#define IDC_COMBO_FILTER_FILE           1112
#define IDC_COMBO_FILTER_TITLE          1113
#define IDC_COMBO_FILTER_GAME           1114
#define IDC_COMBO_FILTER_ARTIST         1115
#define IDC_COMBO_FILTER_DUMPER         1116
#define IDC_CHECK_SHOW_VISUALIZATION    1117
#define IDC_COMBO_FILTER_DATE           1117
#define IDC_COMBO_FILTER_COMMENT        1118
#define IDC_COMBO_FILTER_LENGTH         1119
#define IDC_COMBO_FILTER_FADE           1120
#define IDC_BUTTON_FILTER_APPLY         1121
#define IDC_BUTTON_TC_RESET             1122
#define IDC_CHECK_AUTO_ADVANCE          1123
#define IDC_COMBO_VIS_MODE              1125
#define IDC_COMBO_FILTER_PUBLISHER      1125
#define IDC_CHECK_PC_PUBLISHER          1126
#define IDC_COMBO_VIS_PRIORITY          1128
#define ID_FILE_PROPERTIES              32773
#define ID_FILE_EXIT                    32774
#define ID_EDIT_GOTO                    32777
#define ID_VIEW_REFRESH                 32779
#define ID_OPTIONS_CONFIGURE            32781
#define ID_HELP_CONTENTS                32782
#define ID_HELP_ABOUTSUPERJUKEBOX       32783
#define ID_VIEW_STATUSBAR               40001
#define ID_VIEW_TOOLBARS_STANDARDBUTTONS 40002
#define ID_VIEW_TOOLBARS_TEXTLABELS     40003
#define ID_VIEW_TOOLBARS_PICTURES       40006
#define ID_EDIT_DELETE                  40007
#define ID_VIEW_FILTER                  40009
#define ID_VIEW_TOOLBARS_CUSTOMIZE      40010
#define ID_EDIT_EDITITEM                40011
#define ID_VIEW_TITLEBAR                40013
#define ID_VIEW_MENU                    40014
#define ID_OPTIONS_SAVESETTINGSONEXIT   40016
#define ID_OPTIONS_SAVESETTINGSNOW      40017
#define ID_OPTIONS_RESTOREDEFAULTSETTINGS 40018
#define ID_WINDOWS_FILELIST             40019
#define ID_WINDOWS_PLAYLIST             40020
#define ID_WINDOWS_CONTROLPANEL         40021
#define ID_WINDOWS_VISUALIZER           40022
#define ID_WINDOWS_TILEHORIZONTALLY     40023
#define ID_WINDOWS_TILEVERTICALLY       40024
#define ID_VIEW_SHUFFLE                 40025
#define ID_FILE_IMPORTID666TAGS         40026
#define ID_VIEW_TOOLBARS_SOURCEBAR      40027
#define ID_VIEW_RESIZECOLUMNS           40028
#define ID_FILE_EXPORTID666TAGS         40029
#define ID_FOCUSLOCATION                40030
#define ID_VIEW_TOOLBARS_WRAP           40031
#define ID_FILE_SAVEASHTML              40032
#define ID_MUTE0                        40033
#define ID_MUTE1                        40034
#define ID_MUTE2                        40035
#define ID_MUTE3                        40036
#define ID_MUTE4                        40037
#define ID_MUTE5                        40038
#define ID_MUTE6                        40039
#define ID_MUTE7                        40040
#define ID_MUTEALL                      40041
#define ID_EDIT_INVERT_SELECTION        40042
#define IDS_FILE_MENU                   57643
#define IDS_EDIT_MENU                   57644
#define IDS_VIEW_MENU                   57645
#define IDS_OPTIONS_MENU                57646
#define IDS_HELP_MENU                   57647
#define IDS_WINDOWS_MENU                57648

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         40043
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
